
export MAT_PATH=$MAT_PATH"/home/grads/a/aznaveh/SuiteSparse/ParU/"
echo "========494_bus.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/ParUTst/494_bus/494_bus.mtx
echo "========tumorAntiAngiogenesis_2.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/tumorAntiAngiogenesis_2/tumorAntiAngiogenesis_2.mtx
echo "========olm500.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/olm500/olm500.mtx
echo "========dwt_878.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/dwt_878/dwt_878.mtx
#echo "========lpi_woodinfe_b.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_woodinfe/lpi_woodinfe_b.mtx
#echo "========lpi_woodinfe_lo.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_woodinfe/lpi_woodinfe_lo.mtx
#echo "========lpi_woodinfe_z0.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_woodinfe/lpi_woodinfe_z0.mtx
#echo "========lpi_woodinfe_c.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_woodinfe/lpi_woodinfe_c.mtx
#echo "========lpi_woodinfe.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_woodinfe/lpi_woodinfe.mtx
#echo "========lpi_woodinfe_hi.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_woodinfe/lpi_woodinfe_hi.mtx
#echo "========curtis54.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/curtis54/curtis54.mtx
echo "========adder_dcop_05.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/adder_dcop_05/adder_dcop_05.mtx
echo "========bayer10.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/bayer10/bayer10.mtx
#echo "========lpi_ex72a_c.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_ex72a/lpi_ex72a_c.mtx
#echo "========lpi_ex72a_b.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_ex72a/lpi_ex72a_b.mtx
#echo "========lpi_ex72a_z0.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_ex72a/lpi_ex72a_z0.mtx
#echo "========lpi_ex72a.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_ex72a/lpi_ex72a.mtx
#echo "========lpi_ex72a_hi.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_ex72a/lpi_ex72a_hi.mtx
#echo "========lpi_ex72a_lo.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_ex72a/lpi_ex72a_lo.mtx
#echo "========gas_sensor_C.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/gas_sensor/gas_sensor_C.mtx
#echo "========gas_sensor_B.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/gas_sensor/gas_sensor_B.mtx
#echo "========gas_sensor_E.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/gas_sensor/gas_sensor_E.mtx
#echo "========gas_sensor.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/gas_sensor/gas_sensor.mtx
#echo "========Dubcova3.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/Dubcova3/Dubcova3.mtx
echo "========rajat01.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/rajat01/rajat01.mtx
echo "========rajat19.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/rajat19/rajat19.mtx
#echo "========west0132.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0132/west0132.mtx
#echo "========nos4.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/nos4/nos4.mtx
#echo "========west1505.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west1505/west1505.mtx
#echo "========west0381.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0381/west0381.mtx
#echo "========1138_bus.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/1138_bus/1138_bus.mtx
#echo "========bcsstm25.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm25/bcsstm25.mtx
#echo "========cage15.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/cage15/cage15.mtx
#echo "========west0989.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0989/west0989.mtx
#echo "========west0497.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0497/west0497.mtx
#echo "========west0167.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0167/west0167.mtx
#echo "========Trefethen_20b.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/Trefethen_20b/Trefethen_20b.mtx
#echo "========west0479.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0479/west0479.mtx
#echo "========west2021.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west2021/west2021.mtx
#echo "========lp_kb2_b.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lp_kb2/lp_kb2_b.mtx
#echo "========lp_kb2_c.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lp_kb2/lp_kb2_c.mtx
#echo "========lp_kb2_z0.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lp_kb2/lp_kb2_z0.mtx
#echo "========lp_kb2_hi.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lp_kb2/lp_kb2_hi.mtx
#echo "========lp_kb2.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lp_kb2/lp_kb2.mtx
#echo "========lp_kb2_lo.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lp_kb2/lp_kb2_lo.mtx
#echo "========torso3.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/torso3/torso3.mtx
#echo "========adder_dcop_07.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/adder_dcop_07/adder_dcop_07.mtx
echo "========gent113.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/gent113/gent113.mtx
echo "========xenon1.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/xenon1/xenon1.mtx
#echo "========pwtk.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/pwtk/pwtk.mtx
#echo "========mesh1em6.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/mesh1em6/mesh1em6.mtx
#echo "========mesh1em6_coord.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/mesh1em6/mesh1em6_coord.mtx
#echo "========LF10_B.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/LF10/LF10_B.mtx
#echo "========LF10_C.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/LF10/LF10_C.mtx
#echo "========LF10_E.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/LF10/LF10_E.mtx
#echo "========LF10_M.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/LF10/LF10_M.mtx
#echo "========LF10.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/LF10/LF10.mtx
#echo "========west0655.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0655/west0655.mtx
#echo "========para-4_b.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/para-4/para-4_b.mtx
#echo "========para-4.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/para-4/para-4.mtx
#echo "========Lin.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/Lin/Lin.mtx
#echo "========nos1.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/nos1/nos1.mtx
#echo "========mesh1em1_coord.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/mesh1em1/mesh1em1_coord.mtx
#echo "========mesh1em1.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/mesh1em1/mesh1em1.mtx
#echo "========west0156.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/west0156/west0156.mtx
#echo "========twotone.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/twotone/twotone.mtx
#echo "========Trefethen_20.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/Trefethen_20/Trefethen_20.mtx
#echo "========circuit5M.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/circuit5M/circuit5M.mtx
#echo "========c-62_b.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/c-62/c-62_b.mtx
echo "========c-62.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/c-62/c-62.mtx
#echo "========bcsstm05.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm05.mtx
#echo "========bcsstm01.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm01.mtx
#echo "========az11_11.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/az11_11.mtx
#echo "========LFAT5.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/LFAT5.mtx
#echo "========lpi_galenet_transposed.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpi_galenet_transposed.mtx
#echo "========bcsstm20.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm20.mtx
#echo "========mesh1e1_coord.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/mesh1e1_coord.mtx
#echo "========bcsstm02.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm02.mtx
#echo "========bcsstk22.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstk22.mtx
#echo "========tmp.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/tmp.mtx
#echo "========mesh1e1.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/mesh1e1.mtx
#echo "========bcsstm22.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm22.mtx
#echo "========bcsstm06.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm06.mtx
#echo "========bcsstk03.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstk03.mtx
#echo "========ex5.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/ex5.mtx
#echo "========lpk_b2_transposed.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/lpk_b2_transposed.mtx
#echo "========bcsstk01.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstk01.mtx
#echo "========bcsstm19.mtx========"
#./x_brutal_test <$MAT_PATH/Matrix/ParUTst/bcsstm19.mtx
echo "========hangGlider_2.mtx========"
./x_quick_test <$MAT_PATH/Matrix/ParUTst/hangGlider_2/hangGlider_2.mtx
echo "========Tina_AskCal.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/Tina_AskCal.mtx
echo "========GD98_a.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/GD98_a.mtx
echo "========a0.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/a0.mtx
echo "========a1.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/a1.mtx
echo "========Tina_AskCal_perm.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/Tina_AskCal_perm.mtx
echo "========ash219.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/ash219.mtx
echo "========lp_e226.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/lp_e226.mtx
echo "========r2.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/r2.mtx
echo "========LFAT5.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/LFAT5.mtx
echo "========west0067.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/west0067.mtx
echo "========arrow.mtx========"
./x_quick_test <$MAT_PATH/Matrix/arrow.mtx
echo "========a2.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/a2.mtx
echo "========az88.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/az88.mtx
echo "========young1c.mtx========"
./x_quick_test <$MAT_PATH/Matrix/young1c.mtx
echo "========s32.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/s32.mtx
echo "========lp_share1b.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/lp_share1b.mtx
echo "========cage3.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/cage3.mtx
echo "========b1_ss.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/b1_ss.mtx
echo "========nf0_l.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/nf0_l.mtx
echo "========lfat5b.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/lfat5b.mtx
echo "========c32.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/c32.mtx
echo "========bfwa62.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/bfwa62.mtx
echo "========Ragusa16.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/Ragusa16.mtx
echo "========lp_e226_transposed.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/lp_e226_transposed.mtx
echo "========row0.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/row0.mtx
echo "========Groebner_id2003_aug.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/Groebner_id2003_aug.mtx
echo "========c2.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/c2.mtx
echo "========a4.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/a4.mtx
echo "========problem.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/problem.mtx
echo "========permuted_b1_ss.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/permuted_b1_ss.mtx
echo "========nf0.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/nf0.mtx
echo "========pwr01b.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/pwr01b.mtx
echo "========n3c4-b4.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/n3c4-b4.mtx
echo "========Franz6_id1959_aug.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/Franz6_id1959_aug.mtx
echo "========Ragusa16_pattern.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/Ragusa16_pattern.mtx
echo "========temp.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/temp.mtx
echo "========cage5.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/cage5.mtx
echo "========lpi_itest6.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/lpi_itest6.mtx
echo "========a04.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/a04.mtx
echo "========lpi_galenet.mtx========"
./x_brutal_test <$MAT_PATH/Matrix/lpi_galenet.mtx
